### ISSUE TITLE
Highlighted groups are not working properly

### ISSUE THREAD

**Issue by Pkcarreno** [MyyPo/borrowed.nvim#7]
While I am trying to adjust some plugins with this scheme, when using the highlight groups, they do not map properly.

In config:
```lua
  {
    "myypo/borrowed.nvim",
    lazy = true,
    priority = 1000,
    opts = {
      transparent = true,
      groups = {
        all = {
          DashboardShortCut = { fg = "yell" },
          DashboardHeader = { fg = "yell" },
          DashboardCenter = { fg = "yell" },
          DashboardFooter = { fg = "yell", style = "italic" },
        },
      },
    },
  },

```

This should only affect the dashboard plugin, this is how it looks:
![image](https://github.com/MyyPo/borrowed.nvim/assets/34664891/55ca6e26-6ff3-4989-9e4d-1fc5951a2c8e)

Which is exactly the same as how it looks by default. If I use hex values, it doesn't take them either.

I'm using Lazyvim as base config.

Btw, thanks for this scheme, I'm looking forward to integrating it completely in my config 👍

**Comment by myypo** [comment]
Hi. There seem to be a mistake in how you are trying to change settings. With this plugin you have to pass settings into the setup function and have groups nested under overrides. It seems to be fixing it for me. Here is the edited code:

```lua
return {
	"myypo/borrowed.nvim",
	dev = true,
	lazy = false,
	priority = 1000,

	config = function()
		require("borrowed").setup({
			transparent = true,

			overrides = {
				groups = {
					all = {
						DashboardShortCut = { fg = "yell" },
						DashboardHeader = { fg = "yell" },
						DashboardCenter = { fg = "yell" },
						DashboardFooter = { fg = "yell", style = "italic" },
					},
				},
			},
		})

		vim.cmd("colorscheme mayu")
	end,
}

```

**Comment by Pkcarreno** [comment]
Ohh, ok, I thought overrides was for strategy only.

Thank you very much for the quick response, now it works as expected.
